### PR TITLE
Update for PHP 7.3 compatibility

### PR DESCRIPTION
**Pull request by olimortimer**
Changed `continue` to `continue 2` - see #241

### CODE REVIEW

**Comment by yiiprogrammer** [comment]
Thanks! works again

**Comment by willishq** [comment]
Checking the repository, this PR only patches one file's `continue`'s. There are a couple more which need addressing.

**Comment by olimortimer** [comment]
> Checking the repository, this PR only patches one file's `continue`'s. There are a couple more which need addressing.

We await your PR!

**Comment by michabbb** [comment]
does really someone believe, that this project still is alive and that any PR will be accepted anytime in the future? i don´t.
my advise to everybody here: try [wsdl2php](https://github.com/WsdlToPhp/PackageGenerator), my few tests showed me: it´s worth a shot.
there are some issues and it makes sense to build some wrappers, but then, it looks very promising.
i tested with php5 and added my own stuff, same can be done with php7, [feel free to take a look into it](https://github.com/michabbb/wsdl2php-ebay-testing/tree/php5).

**Comment by shreyanshpanchal** [comment]
@davidtsadler Can you please merge this one?

**Comment by shreyanshpanchal** [comment]
> Checking the repository, this PR only patches one file's `continue`'s. There are a couple more which need addressing.

I couldn't find any other occurances of `continue` which needed addressal.

**Comment by rbur0425** [comment]
thanks for this fix!

**Pull request closed without merging**
