### PR TITLE
Refactoring php-doc and code.

### PR DESCRIPTION
**Pull request by voskobovich**
Your repository contained errors which were displayed in my IDE and caused discomfort. I corrected them, and placed in the TODO that require your attention.

### CODE REVIEW

**Comment by davidtsadler** [comment]
Big thanks for the PR. I've been thinking about correcting a lot of the source documentation for a while. This should save me a lot of time. I'll take a look at the changes before integrating them and I'll also look at what I can fix with regards to the TODO items.

**Comment by voskobovich** [comment]
No problem :)
You should use PhpStorm and its function code analysis on your project to identify mistakes documentation. It saves a lot of time.

**Comment by voskobovich** [comment]
How are you doing with checking this PR?

**Comment by davidtsadler** [comment]
At the moment I'm very busy with updating the SDK so that it is compatible with the new REST services. I will look at merging these changes once I have finished, as there are going to be a lot of new files introduced into the SDK that may not be compatible with this PR. It's going to be easier for me to finish the REST services and then look at merging your changes. I should have said something earlier but I've been busy so apologies for not getting back sooner.

**Pull request closed without merging**
